# Generated by Django 6.0.5 on 2026-05-19 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
    ]
