# Generated by Django 6.0.5 on 2026-05-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_plannersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannersettings',
            name='exam_date',
            field=models.DateField(default='2026-05-19'),
            preserve_default=False,
        ),
    ]
