# Generated by Django 6.0.4 on 2026-05-19 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_plannersettings_exam_date'),
        ('subjects', '0003_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='studytask',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
    ]
